import { Theme } from "@emotion/react";

export const theme: Theme = {
  pelette: {
    background: {
      body: "var(--color-body)",
      surface: "var(--color-surface)",
    },
    common: {
      black: "black",
      white: "white",
    },
    divider: "var(--color-border)",
    text: {
      primary: "var(--color-text-primary)",
      secondary: "var(--color-text-secondary)",
      tertiary: "var(--color-text-tertiary)",
      icon: "var(--color-text-icon)",
    },
    primary: {
      main: "var(--color-primary-main)",
      light: "var(--color-primary-light)",
      dark: "var(--color-primary-dark)",
      contrastText: "var(--color-primary-contrast-text)",
      50: "var(--palette-primary-50)",
      100: "var(--palette-primary-100)",
      200: "var(--palette-primary-200)",
      300: "var(--palette-primary-300)",
      400: "var(--palette-primary-400)",
      500: "var(--palette-primary-500)",
      600: "var(--palette-primary-600)",
      700: "var(--palette-primary-700)",
      800: "var(--palette-primary-800)",
      900: "var(--palette-primary-900)",
    },
    success: {
      main: "var(--color-success-main)",
      light: "var(--color-success-light)",
      dark: "var(--color-success-dark)",
      contrastText: "var(--color-success-contrast-text)",
      50: "var(--palette-success-50)",
      100: "var(--palette-success-100)",
      200: "var(--palette-success-200)",
      300: "var(--palette-success-300)",
      400: "var(--palette-success-400)",
      500: "var(--palette-success-500)",
      600: "var(--palette-success-600)",
      700: "var(--palette-success-700)",
      800: "var(--palette-success-800)",
      900: "var(--palette-success-900)",
    },
    secondary: {
      main: "var(--color-secondary-main)",
      light: "var(--color-secondary-light)",
      dark: "var(--color-secondary-dark)",
      contrastText: "var(--color-secondary-contrast-text)",
      50: "var(--palette-secondary-50)",
      100: "var(--palette-secondary-100)",
      200: "var(--palette-secondary-200)",
      300: "var(--palette-secondary-300)",
      400: "var(--palette-secondary-400)",
      500: "var(--palette-secondary-500)",
      600: "var(--palette-secondary-600)",
      700: "var(--palette-secondary-700)",
      800: "var(--palette-secondary-800)",
      900: "var(--palette-secondary-900)",
    },
    error: {
      main: "var(--color-error-main)",
      light: "var(--color-error-light)",
      dark: "var(--color-error-dark)",
      contrastText: "var(--color-error-contrast-text)",
      50: "var(--palette-error-50)",
      100: "var(--palette-error-100)",
      200: "var(--palette-error-200)",
      300: "var(--palette-error-300)",
      400: "var(--palette-error-400)",
      500: "var(--palette-error-500)",
      600: "var(--palette-error-600)",
      700: "var(--palette-error-700)",
      800: "var(--palette-error-800)",
      900: "var(--palette-error-900)",
    },
    warning: {
      main: "var(--color-warning-main)",
      light: "var(--color-warning-light)",
      dark: "var(--color-warning-dark)",
      contrastText: "var(--color-warning-contrast-text)",
      50: "var(--palette-warning-50)",
      100: "var(--palette-warning-100)",
      200: "var(--palette-warning-200)",
      300: "var(--palette-warning-300)",
      400: "var(--palette-warning-400)",
      500: "var(--palette-warning-500)",
      600: "var(--palette-warning-600)",
      700: "var(--palette-warning-700)",
      800: "var(--palette-warning-800)",
      900: "var(--palette-warning-900)",
    },
    neutral: {
      main: "var(--color-neutral-main)",
      light: "var(--color-neutral-light)",
      dark: "var(--color-neutral-dark)",
      contrastText: "var(--color-neutral-contrast-text)",
      50: "var(--palette-neutral-50)",
      100: "var(--palette-neutral-100)",
      200: "var(--palette-neutral-200)",
      300: "var(--palette-neutral-300)",
      400: "var(--palette-neutral-400)",
      500: "var(--palette-neutral-500)",
      600: "var(--palette-neutral-600)",
      700: "var(--palette-neutral-700)",
      800: "var(--palette-neutral-800)",
      900: "var(--palette-neutral-900)",
    },
    yellow: {
      main: "var(--color-yellow-main)",
      light: "var(--color-yellow-light)",
      dark: "var(--color-yellow-dark)",
      contrastText: "var(--color-yellow-contrast-text)",
      50: "var(--palette-yellow-50)",
      100: "var(--palette-yellow-100)",
      200: "var(--palette-yellow-200)",
      300: "var(--palette-yellow-300)",
      400: "var(--palette-yellow-400)",
      500: "var(--palette-yellow-500)",
      600: "var(--palette-yellow-600)",
      700: "var(--palette-yellow-700)",
      800: "var(--palette-yellow-800)",
      900: "var(--palette-yellow-900)",
    },
    brown: {
      main: "var(--color-brown-main)",
      light: "var(--color-brown-light)",
      dark: "var(--color-brown-dark)",
      contrastText: "var(--color-brown-contrast-text)",
      50: "var(--palette-brown-50)",
      100: "var(--palette-brown-100)",
      200: "var(--palette-brown-200)",
      300: "var(--palette-brown-300)",
      400: "var(--palette-brown-400)",
      500: "var(--palette-brown-500)",
      600: "var(--palette-brown-600)",
      700: "var(--palette-brown-700)",
      800: "var(--palette-brown-800)",
      900: "var(--palette-brown-900)",
    },
    lime: {
      main: "var(--color-lime-main)",
      light: "var(--color-lime-light)",
      dark: "var(--color-lime-dark)",
      contrastText: "var(--color-lime-contrast-text)",
      50: "var(--palette-lime-50)",
      100: "var(--palette-lime-100)",
      200: "var(--palette-lime-200)",
      300: "var(--palette-lime-300)",
      400: "var(--palette-lime-400)",
      500: "var(--palette-lime-500)",
      600: "var(--palette-lime-600)",
      700: "var(--palette-lime-700)",
      800: "var(--palette-lime-800)",
      900: "var(--palette-lime-900)",
    },
  },
  shape: {
    borderRadius: 4,
  },
};
